# Generated by Django 4.2.17 on 2024-12-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='mobil_number',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
